[tool.poetry]
name = "subfinder"
version = "1.0.9"
description = "subfinder -- a general finder for subtitles"
authors = ["ausaki <ljm51689@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*"
requests = "*"
bs4 = "^0.0.1"
lxml = "*"
gevent = "^1.4.0"
rarfile = "*"
six = "*"

[tool.poetry.dev-dependencies]
tox = "*"
twine = "*"
pyinstaller = "*"
autopep8 = "*"
rope = "*"
pytest = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
